In [104]:
import numpy as np

In [105]:
a = np.arange(-1.0,2.0,1)

In [56]:
scores = np.vstack([a,np.ones_like(a), 0.2*np.ones_like(a)])

In [106]:
str(type(scores)) == "<type 'numpy.ndarray'>"
    
        


True

In [57]:
scores

array([[-1. ,  0. ,  1. ],
       [ 1. ,  1. ,  1. ],
       [ 0.2,  0.2,  0.2]])

In [65]:
scores[0:1]

array([[-1.,  0.,  1.]])

In [69]:
scores[1:2]

array([[ 1.,  1.,  1.]])

In [67]:
scores[1:]

array([[ 1. ,  1. ,  1. ],
       [ 0.2,  0.2,  0.2]])

In [85]:
counter=0
xps = []
for row in scores:
    counter = counter +1
    if counter ==1:
        for elem in row:
            xps.append( np.exp(elem))
    #print(row, counter)

In [86]:
xps

[0.36787944117144233, 1.0, 2.7182818284590451]

In [88]:
scores[1] = xps

In [93]:
sumPorbs = np.sum(xps)

In [94]:
sumPorbs

4.0861612696304874

In [89]:
scores

array([[-1.        ,  0.        ,  1.        ],
       [ 0.36787944,  1.        ,  2.71828183],
       [ 0.2       ,  0.2       ,  0.2       ]])

In [97]:
probs = [x/sumPorbs for x in xps]

In [98]:
probs


[0.090030573170380462, 0.24472847105479767, 0.6652409557748219]

In [99]:
scores[2] = probs

In [100]:
scores

array([[-1.        ,  0.        ,  1.        ],
       [ 0.36787944,  1.        ,  2.71828183],
       [ 0.09003057,  0.24472847,  0.66524096]])

In [101]:
scores[2]

array([ 0.09003057,  0.24472847,  0.66524096])

In [103]:
type(scores[2])

numpy.ndarray